algoritmo "semnome"
// Função :
// Autor :
// Data : 22/03/2019
// Seção de Declarações
var
a,b,c:inteiro
inicio
// Seção de Comandos
leia(a)
leia(b)
leia(c)
//se(a<b+c)entao
//  se(b<a+c)entao
//    se(c<a+b)entao
Escreval("E triangulo")
se((a=b) E (a=c) E (b=c))entao
   escreval("Equilatero")
senao
   se((a=/=b) E (a=/=c) E (b=/=c))entao
      escreval("Escaleno")
   senao
      escreval("Isosceles")
   fimse
fimse
//   fimse
//fimse
//fimse

fimalgoritmo
